### ISSUE TITLE
一个多月没更新啦！

### ISSUE THREAD

**Issue by zmrenwu** [Allianzcortex/MusicRecommendSystem#1]
一个多月没更新啦！

**Comment by Allianzcortex** [comment]
@zmrenwu 因为正在写毕业论文啊⊙﹏⊙b汗～37000字论文用 `paperpass` 查重10%，好多重复都是完全没有道理的～ 虽然重复率不高但还是需要改,看能不能拿优  还要看数据挖掘方面的一些内容～  最近事情比较多，好多功能就先放下了。保证这是一个持续更新的项目哈，会一直完善的

**Comment by zmrenwu** [comment]
好，准备读研了么？做数据挖掘方向？我现在研一，做的数据挖掘。


发自 网易邮箱大师
On 05/22/2016 18:30, hzcortex wrote:

@zmrenwu 因为正在写毕业论文啊⊙﹏⊙b汗～37000字论文用 paperpass 查重10%，好多重复都是完全没有道理的～ 虽然重复率不高但还是需要改,看能不能拿优 还要看数据挖掘方面的一些内容～ 最近事情比较多，好多功能就先放下了。保证这是一个持续更新的项目哈，会一直完善的

**Comment by Allianzcortex** [comment]
@zmrenwu  不是啊。。去的帝都一家公司，offer 是数据挖掘岗；你也在搞数据挖掘吗？太巧了，以后有机会多多交流呀

**Comment by zmrenwu** [comment]
嗯，好的，前面在关注你的项目。最近我组织了一个django学习开发小组，正在开发一个django中文社区。本想如果你有兴趣的话看能不能把你的项目合并进来。不过还是先忙你的事情吧。


发自 网易邮箱大师
在2016年05月22日 18:35，hzcortex 写道:

@zmrenwu 不是啊。。去的帝都一家公司，offer 是数据挖掘岗；你也在搞数据挖掘吗？太巧了，以后有机会多多交流呀

**Comment by Allianzcortex** [comment]
@zmrenwu  这是好事情啊:-) with best luck~

**Comment by zmrenwu** [comment]
thank you！


发自 网易邮箱大师
On 05/22/2016 19:04, hzcortex wrote:

@zmrenwu 这是好事情啊:-) with best luck~
